/** This is the Sec2 package containing XML handlers handling incoming
 * XML events. The incoming events are generated by the XML processors from
 * the package org.sec2.pipeline.
 */
package org.sec2.pipeline.handlers;

