/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeRSA */

#ifndef _Included_NativeRSA
#define _Included_NativeRSA
#ifdef __cplusplus
extern "C" {
#endif
#ifndef BYTEMOD
#define BYTEMOD 0xFF
#endif
/*
 * Class:     NativeRSA
 * Method:    NativeExponentiate
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cipher_NativeRSA_NativeExponentiate
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);


#ifdef __cplusplus
}
#endif
#endif
