/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniTest */

#ifndef _Included_JniTest
#define _Included_JniTest
#ifdef __cplusplus
extern "C" {
#endif
#ifndef BYTEMOD
#define BYTEMOD 0xFF
#endif
JNIEXPORT jbyteArray JNICALL Java_cipher_NativeAES_aesECBEnc(
	JNIEnv* env,
	jclass jcls,
	jbyteArray jkey,
	jbyteArray jdata);

JNIEXPORT jbyteArray JNICALL Java_cipher_NativeAES_aesECBDec(
	JNIEnv* env,
	jclass jcls,
	jbyteArray jkey,
	jbyteArray jdata);

JNIEXPORT jbyteArray JNICALL Java_cipher_NativeAES_aesCBCEnc(
	JNIEnv* env,
	jclass jcls,
	jbyteArray jkey,
	jbyteArray jiv,
	jbyteArray jdata);

JNIEXPORT jbyteArray JNICALL Java_cipher_NativeAES_aesCBCDec (
    JNIEnv* env,
    jclass jcls,
    jbyteArray jkey,
    jbyteArray jiv,
    jbyteArray jdata);

JNIEXPORT jbyteArray JNICALL Java_cipher_NativeAES_aesECBEncFile (
	JNIEnv* env,
	jclass jcls,
	jbyteArray jkey,
	jbyteArray jdata);


#ifdef __cplusplus
}
#endif
#endif
