/*
 * NativeGCM.h
 *
 *  Created on: 10.06.2013
 *      Author: Dominik
 */

/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class JniTest */
#include <jni.h>

#ifndef NATIVEGCM_H_
#define NATIVEGCM_H_
#ifdef __cplusplus
extern "C" {
#endif


//#include "aesGcm.h"
JNIEXPORT void JNICALL Java_cipher_NativeGCM_gcmEncrypt(
	JNIEnv* env,
	jclass jcls,
	jbyteArray result,
	jbyteArray T,
	jbyteArray jkey,
	jbyteArray jdata,
	jbyteArray iv,
	jbyteArray aad);

JNIEXPORT jboolean JNICALL Java_cipher_NativeGCM_gcmDecrypt(
	JNIEnv* env,
	jclass jcls,
	jbyteArray result,
	jbyteArray T,
	jbyteArray jkey,
	jbyteArray jdata,
	jbyteArray iv,
	jbyteArray aad);
#ifdef __cplusplus
}
#endif
#endif /* NATIVEGCM_H_ */
