CREATE DATABASE sec2test;
USE sec2test;

CREATE TABLE IF NOT EXISTS users (
	id INT NOT NULL AUTO_INCREMENT UNIQUE
,	pk_hash VARBINARY(64) NOT NULL UNIQUE
,	email VARCHAR(254) NOT NULL UNIQUE
,	pkc BLOB NOT NULL
,	sign_pkc BLOB NOT NULL
,	status INT
,	challenge BINARY(64) NOT NULL
,   registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
,	PRIMARY KEY (id, pk_hash, email)
) ENGINE=MyISAM;


CREATE TABLE IF NOT EXISTS groups (
	id INT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY
,	operator VARCHAR(254) NOT NULL
,	name VARCHAR(255) NOT NULL UNIQUE
,	FOREIGN KEY (operator) REFERENCES users(id)
)ENGINE=MyISAM;

CREATE TABLE IF NOT EXISTS group_members (
	user_ref INT NOT NULL
,	group_ref INT NOT NULL
,	FOREIGN KEY (user_ref) REFERENCES users(id)
,	FOREIGN KEY (group_ref) REFERENCES groups(id)
,   UNIQUE INDEX (user_ref, group_ref)
)ENGINE=MyISAM;
