/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sec2.token.tools;

import javax.swing.JOptionPane;
import org.sec2.token.ReturnCodes;
import org.sec2.token.IToken;
import org.sec2.token.IToken.TokenStatus;
import org.sec2.token.TokenHelper;
import org.sec2.token.exceptions.TokenException;
import org.sec2.token.hwtoken.HardwareToken;
import org.sec2.token.keys.ByteArray;
import org.sec2.token.keys.ServerKey;
import org.sec2.token.keys.UserKey;

/**
 *
 * @author benedikt
 */
public class TokenView extends javax.swing.JFrame {

    private TokenHelper myTool;

    /**
     * Creates new form TokenView
     */
    public TokenView() {
        initComponents();

        myTool = new TokenHelper(new HardwareToken());
        loadTokenStatus();
    }

    private void loadTokenStatus() {
        try {
            TokenStatus cStatus = myTool.getStatus();
            String verStr = myTool.getVersion();

            lblVersion.setText(verStr);
            lblPINSet.setText(cStatus.pinIsChanged ? "Yes" : "No");
            lblPUKSet.setText(cStatus.pukIsChanged ? "Yes" : "No");
            lblUKEYSet.setText(cStatus.ukeysAreGenerated ? "Yes" : "No");
            lblSKEYSet.setText(cStatus.skeyIsSet ? "Yes" : "No");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Error while reading contents:\n\n " + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPanel = new javax.swing.JTabbedPane();
        panelInfo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblSKEYSet = new javax.swing.JLabel();
        lblUKEYSet = new javax.swing.JLabel();
        lblPUKSet = new javax.swing.JLabel();
        lblPINSet = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();
        panelClusterKeys = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstKeyIds = new javax.swing.JList();
        panelServer = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblServerExp = new javax.swing.JLabel();
        lblServerMod = new javax.swing.JLabel();
        panelUser = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblUserEncExp = new javax.swing.JLabel();
        lblUserEncMod = new javax.swing.JLabel();
        panelUser1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblUserSigExp = new javax.swing.JLabel();
        lblUserSigMod = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtPIN = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btnReadToken = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sec2 TokenView");
        setResizable(false);

        tabbedPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tabbedPanel.setEnabled(false);

        jLabel3.setText("Applet Version: ");

        jLabel4.setText("UKEY is set:");

        jLabel7.setText("PIN is set:");

        jLabel10.setText("PUK is set:");

        jLabel11.setText("SKEY is set:");

        lblSKEYSet.setText("?");

        lblUKEYSet.setText("?");

        lblPUKSet.setText("?");

        lblPINSet.setText("?");

        lblVersion.setText("?");

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSKEYSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUKEYSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPUKSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPINSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVersion, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblVersion))
                .addGap(30, 30, 30)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblPINSet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblPUKSet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblUKEYSet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblSKEYSet))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Info", panelInfo);

        panelClusterKeys.setBorder(null);
        panelClusterKeys.setEnabled(false);

        jLabel2.setText("Available ClusterKeys:");

        lstKeyIds.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstKeyIds);

        javax.swing.GroupLayout panelClusterKeysLayout = new javax.swing.GroupLayout(panelClusterKeys);
        panelClusterKeys.setLayout(panelClusterKeysLayout);
        panelClusterKeysLayout.setHorizontalGroup(
            panelClusterKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClusterKeysLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelClusterKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClusterKeysLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelClusterKeysLayout.setVerticalGroup(
            panelClusterKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClusterKeysLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPanel.addTab("ClusterKeys", panelClusterKeys);

        panelServer.setBorder(null);
        panelServer.setEnabled(false);

        jLabel9.setText("Exponent:");

        jLabel8.setText("Modulus:");

        lblServerExp.setFont(new java.awt.Font("Courier 10 Pitch", 0, 10)); // NOI18N
        lblServerExp.setText("?");

        lblServerMod.setFont(new java.awt.Font("Courier 10 Pitch", 0, 10)); // NOI18N
        lblServerMod.setText("?");
        lblServerMod.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout panelServerLayout = new javax.swing.GroupLayout(panelServer);
        panelServer.setLayout(panelServerLayout);
        panelServerLayout.setHorizontalGroup(
            panelServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblServerExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelServerLayout.createSequentialGroup()
                        .addGroup(panelServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(0, 234, Short.MAX_VALUE))
                    .addComponent(lblServerMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelServerLayout.setVerticalGroup(
            panelServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblServerExp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblServerMod, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPanel.addTab("ServerKey", panelServer);

        panelUser.setBorder(null);
        panelUser.setEnabled(false);

        jLabel5.setText("Exponent:");

        jLabel6.setText("Modulus:");

        lblUserEncExp.setFont(new java.awt.Font("Courier 10 Pitch", 0, 10)); // NOI18N
        lblUserEncExp.setText("?");

        lblUserEncMod.setFont(new java.awt.Font("Courier 10 Pitch", 0, 10)); // NOI18N
        lblUserEncMod.setText("?");
        lblUserEncMod.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout panelUserLayout = new javax.swing.GroupLayout(panelUser);
        panelUser.setLayout(panelUserLayout);
        panelUserLayout.setHorizontalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserEncExp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addGroup(panelUserLayout.createSequentialGroup()
                        .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblUserEncMod, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelUserLayout.setVerticalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserEncExp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserEncMod, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPanel.addTab("UserKeyEnc", panelUser);

        panelUser1.setBorder(null);
        panelUser1.setEnabled(false);

        jLabel12.setText("Exponent:");

        jLabel13.setText("Modulus:");

        lblUserSigExp.setFont(new java.awt.Font("Courier 10 Pitch", 0, 10)); // NOI18N
        lblUserSigExp.setText("?");

        lblUserSigMod.setFont(new java.awt.Font("Courier 10 Pitch", 0, 10)); // NOI18N
        lblUserSigMod.setText("?");
        lblUserSigMod.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout panelUser1Layout = new javax.swing.GroupLayout(panelUser1);
        panelUser1.setLayout(panelUser1Layout);
        panelUser1Layout.setHorizontalGroup(
            panelUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUser1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserSigExp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addGroup(panelUser1Layout.createSequentialGroup()
                        .addGroup(panelUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblUserSigMod, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelUser1Layout.setVerticalGroup(
            panelUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUser1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserSigExp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserSigMod, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPanel.addTab("UserKeySig", panelUser1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Authentication"));

        jLabel1.setText("PIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtPIN)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnReadToken.setText("Query Token");
        btnReadToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadTokenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabbedPanel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReadToken, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReadToken, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String formatHexStr(String hexStr) {
        final short CHARS_PER_LINE = 50;
        String outText;
        short i, charCount;

        outText = "";
        charCount = 0;
        for (i = 0; i < hexStr.length(); i++) {
            charCount++;
            outText += hexStr.charAt(i);
            if ((charCount == CHARS_PER_LINE) && (i + 1 != hexStr.length())) {
                outText += "<br>";
                charCount = 0;
            }
        }

        return "<html>" + outText + "</html>";
    }

    private void btnReadTokenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnReadTokenActionPerformed
        String PIN = txtPIN.getText();

        try {
            lstKeyIds.setListData(myTool.listClusterKeyIds(new ByteArray(PIN)));

            UserKey userKeyEnc = myTool.getUserKeyEnc(new ByteArray(PIN));
            lblUserEncExp.setText(formatHexStr(userKeyEnc.getExponent().toString()));
            lblUserEncMod.setText(formatHexStr(userKeyEnc.getModulus().toString()));

            UserKey userKeySig = myTool.getUserKeySig(new ByteArray(PIN));
            lblUserSigExp.setText(formatHexStr(userKeySig.getExponent().toString()));
            lblUserSigMod.setText(formatHexStr(userKeySig.getModulus().toString()));

            ServerKey serverKey = myTool.getServerKey(new ByteArray(PIN));
            lblServerExp.setText(formatHexStr(serverKey.getExponent().toString()));
            lblServerMod.setText(formatHexStr(serverKey.getModulus().toString()));

            tabbedPanel.setEnabled(true);

            loadTokenStatus();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Error while reading contents:\n\n " + ex);
        }
    }// GEN-LAST:event_btnReadTokenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        // <editor-fold defaultstate="collapsed"
        // desc=" Look and feel setting code (optional) ">
		/*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase
         * /tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TokenView.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TokenView.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TokenView.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TokenView.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TokenView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReadToken;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPINSet;
    private javax.swing.JLabel lblPUKSet;
    private javax.swing.JLabel lblSKEYSet;
    private javax.swing.JLabel lblServerExp;
    private javax.swing.JLabel lblServerMod;
    private javax.swing.JLabel lblUKEYSet;
    private javax.swing.JLabel lblUserEncExp;
    private javax.swing.JLabel lblUserEncMod;
    private javax.swing.JLabel lblUserSigExp;
    private javax.swing.JLabel lblUserSigMod;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JList lstKeyIds;
    private javax.swing.JPanel panelClusterKeys;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelServer;
    private javax.swing.JPanel panelUser;
    private javax.swing.JPanel panelUser1;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JPasswordField txtPIN;
    // End of variables declaration//GEN-END:variables
}
